# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'


target 'gannons' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gannons
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'


  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'gannonsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'gannons-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gannons-tvOS

  target 'gannons-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
